package com.example.demo

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

@RestController
class DummyService {

    // example spring-boot Rest-controller
    @GetMapping("/")
    fun myController() = Person(
            age= 18,
            name = "Eva".toCodeFreeze()
    )

    @GetMapping("/iam")
    fun myOtherController(@RequestParam age: Int): String =
            // switch-case example
            when (age) {
                // example of defining ranges
                in 0..9 -> "you are a child"
                in 10..17 -> "you are a teenager"
                in 18..120 -> "you are adult"
                !in 0..120 -> "this is strange"
                else -> "invalid age"
            }
}

// example for data classes
data class Person(
        val name: String = "Chris", // example for default arguments
        val age: Int,
        var comment: String = "" // a setter will be autogenerated here because 'var' is not final (like 'val')
)

// example for extension functions
fun String.toCodeFreeze(): String = "codefreeze - $this"
